io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
Update the json for new upstream .deb and also libsecret release that works again.
=> Update to 0.22.0

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.29.4

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
This updates the package to the latest version.
Seems to work fine for me. If somebody else could check and merge that would be great.
Thanks
=> Update to 0.33.0

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
Update to LBRY app version 0.35.0 (Franklin)
=> Application Update to Version 0.35.0

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.35.1

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.35.2

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.35.3

io.lbry.lbry-app.json
Closes #34 
Signed-off-by: Michal Konecny <michal.konecny@packetseekers.eu>
=> Update freedesktop runtime to 19.08

io.lbry.lbry-app.json
Signed-off-by: Michal Konecny <michal.konecny@packetseekers.eu>
=> Update to 0.36.0

io.lbry.lbry-app.appdata.xml
[UPDATE] 0.36.0 - Code Name Galileo
=> [UPDATE] 0.36.0 - Code Name Galileo

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.36.1

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
[UPDATE] 0.37.0 - Code name Heisenberg
=> [UPDATE] 0.37.0 - Code name Heisenberg

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
[UPDATE] 0.37.1
Sorry for the delay, was waiting for the RCs to get pushed to an official build.
=> [UPDATE] 0.37.1

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.37.2

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
Pushing the code-testing branch over to master. This includes the update to 0.38.2 from ProfessorDey.
=> Pushing code-testing branch to master - Includes update 0.38.2 update

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.39.0

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.39.1

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.41.0

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.42.0

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.43.0

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.43.3

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.44.0

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
[UPDATE] 0.45.0 - Code name **Mach**
=> [UPDATE] 0.45.0

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
[UPDATE] 0.46.0 -- Code name: Ohm
=> [UPDATE] 0.46.0

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
Updated to latest patch and formatted the XML cleanly.
=> [UPDATE] 0.46.1 & Formatted XML

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
=> [UPDATE] 0.47.0 - Pausch

io.lbry.lbry-app.appdata.xml, io.lbry.lbry-app.json
Sorry, I've been a little MIA. This should resume normal updating between myself and other contributors. If you need a PR reviewed, please ping me or message me directly on Discord, Revolt, or otherwise.
=> [UPDATE] 0.52.6
